### ISSUE TITLE
 Error: Error when validating: Tried to update a non-updatable model

### ISSUE THREAD

**Issue by uonuon** [blockstack-radiks/radiks-server#28]
I was deploying my app and i found this error on my server logs
`
(node:11621) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
0|server   | (node:11621) DeprecationWarning: collection.save is deprecated. Use insertOne, insertMany, updateOne, or updateMany instead.
0|server   | Error: Error when validating: Tried to update a non-updatable model
0|server   |     at errorMessage (/root/servers/dcloud/packages/server/node_modules/radiks-server/app/lib/validator.js:4:9)
0|server   |     at Validator.validatePrevious (/root/servers/dcloud/packages/server/node_modules/radiks-server/app/lib/validator.js:71:7)
0|server   |     at Validator.validate (/root/servers/dcloud/packages/server/node_modules/radiks-server/app/lib/validator.js:17:16)
0|server   |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|server   | Error: Error when validating: Tried to update a non-updatable model
0|server   |     at errorMessage (/root/servers/dcloud/packages/server/node_modules/radiks-server/app/lib/validator.js:4:9)
0|server   |     at Validator.validatePrevious (/root/servers/dcloud/packages/server/node_modules/radiks-server/app/lib/validator.js:71:7)
0|server   |     at Validator.validate (/root/servers/dcloud/packages/server/node_modules/radiks-server/app/lib/validator.js:17:16)
0|server   |     at process._tickCallback (internal/process/next_tick.js:68:7)
`
The app routing throw a bad gateway 502 Error
the error seems that i am updating some models are not updateable, which i think is just `SigningKey`. which is i cannot update a `SigningKey` with a new private key.

but i don't do anything like that in my react app

**Comment by jeffdomke** [comment]
@uonuon did you ever resolve this?
